use_frameworks!

platform :ios, '12.0'

target 'BPContactCenter_Example' do
  pod 'BPContactCenter', :path => '../'
  pod 'Firebase/Messaging'

  target 'BPContactCenter_Tests' do
    inherit! :search_paths

    
  end
end
