use_frameworks!

platform :ios, '12.0'

target 'BPMobileMessaging_Example' do
  pod 'BPMobileMessaging', :path => '../'
  pod 'Firebase/Messaging'

  target 'BPMobileMessaging_Tests' do
    inherit! :search_paths

    
  end
end
